import "./styles/globals.css";

export const metadata = {
  title: "ITB - Login Page",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
